name: Kernel 6.8 build

on:
  push:
  workflow_dispatch:
  pull_request:

jobs: 
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          sudo apt install build-essential linux-headers-6.8.0-1010-azure
          make
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: |
          curl -O https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
          sudo chmod u+x ./checkpatch.pl
          ./checkpatch.pl
