name: Kernel linter

on:
  push:
  workflow_dispatch:
  pull_request:

lint:
  runs-on: ubuntu-24.04
  steps:
    - uses: actions/checkout@v4
    - name: lint
      run: |
        curl -O https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
        sudo chmod u+x ./checkpatch.pl
        ./checkpatch.pl
